In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5,6]) # It will convert into the ndarray

array([2, 3, 4, 5, 6])

In [4]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [6]:
np.array([[2,3,4],[4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [8]:
np.array([[1,2,3,4],[2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [9]:
l=[[1,2,3,4],[2,3,4,5]]

In [10]:
print(l[0][0])

1


In [12]:
# We can also define the dimmension
a = np.array([3,4,5,6],ndmin=5)

In [13]:
print(a)

[[[[[3 4 5 6]]]]]


In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.ndim

2

In [20]:
# Creating the data in the numpy
np.random.randint(1,10,(4,4)) # Rows*Column

array([[3, 4, 7, 6],
       [3, 4, 8, 7],
       [8, 9, 8, 5],
       [4, 8, 5, 5]])

In [23]:
np.random.randint(1,10,(4,4,2)) # Rows=4 and Column=4
# Explanation:- We will get the the array of 4 rows and 2 column and we will get the 4 arrays

array([[[3, 1],
        [9, 8],
        [4, 9],
        [8, 2]],

       [[7, 6],
        [8, 5],
        [5, 5],
        [8, 2]],

       [[5, 5],
        [7, 1],
        [7, 5],
        [4, 3]],

       [[8, 8],
        [6, 7],
        [2, 9],
        [3, 6]]])

In [2]:
# Lecture-2
l=[1,2,3,4,5]


In [3]:
np.array(l) # These will convert the data into the array
# Here the list l only contains the numerical values so it converts the list into the array

array([1, 2, 3, 4, 5])

In [21]:
l1=[4,5,6,7,"sudh",34.565,True]
a1=np.array(l1) # But here in the list l1 the data is present in all data types so it will convert all data in the string

In [33]:
a2=np.array([[1,2,3],[4,5,6]])

In [35]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [25]:
a1.ndim # Only x- axis required

1

In [34]:
a2.ndim # x-y axis required

2

In [36]:
a3.ndim #x-y-z axis required

3

In [39]:
a1.size # Size will always tell you about the total number of elements in the array

7

In [40]:
a2.size

6

In [41]:
a3.size

9

In [42]:
a1.shape  # 1D array 7 elements

(7,)

In [43]:
a2.shape # Rows-2 Columns->2

(2, 3)

In [44]:
a3.shape # Rows->3 cColumns->3 and you have 1 array

(1, 3, 3)

In [46]:
np.random.randint(2,5) # Will give the random integer between 2 to 5

2

In [50]:
np.random.randint(2,50)

31

In [52]:
np.random.randint(2,50,(3,4)) # It will give the random integer in the matrix of 3 rows and 4 columns

array([[20, 17, 43, 17],
       [ 8, 45, 12,  2],
       [12, 44, 18, 42]])

In [54]:
np.random.randint(2,50,(2,3,4)) # Rows->3 Columns->4 and will give you 2 matrix

array([[[25, 49, 27, 42],
        [27, 37, 42, 26],
        [24, 19, 33, 10]],

       [[16, 38, 21, 19],
        [11, 23,  5, 28],
        [33, 45, 43, 31]]])

In [56]:
np.random.rand(2,3) # Will give the 2 rows and 3 columns

array([[0.95938489, 0.87637357, 0.17441325],
       [0.99821312, 0.0016196 , 0.78223279]])

In [59]:
a4=np.random.randn(4,4)# randn generate the dataset which has mean=0 and standard deviation=1

In [60]:
# If we want to change the dimmension of the array means if you want to change the rows and columns
print(a4)

[[-0.34680709  1.4709312  -0.85768024 -1.17870434]
 [-0.18514847 -2.18952486 -0.22503192  1.5702648 ]
 [-0.36792259 -1.1792732   0.67730928 -0.98131141]
 [ 0.16787026  0.42024066  0.78338461 -0.38502844]]


In [62]:
# a4.reshape(3,4) # These will give error because the dimension of a4 is 16 and we are converting it into 12
# Here we have to choose the factor of 16

ValueError: cannot reshape array of size 16 into shape (3,4)

In [63]:
a4.reshape(2,8)

array([[-0.34680709,  1.4709312 , -0.85768024, -1.17870434, -0.18514847,
        -2.18952486, -0.22503192,  1.5702648 ],
       [-0.36792259, -1.1792732 ,  0.67730928, -0.98131141,  0.16787026,
         0.42024066,  0.78338461, -0.38502844]])

In [64]:
a4.reshape(8,2)

array([[-0.34680709,  1.4709312 ],
       [-0.85768024, -1.17870434],
       [-0.18514847, -2.18952486],
       [-0.22503192,  1.5702648 ],
       [-0.36792259, -1.1792732 ],
       [ 0.67730928, -0.98131141],
       [ 0.16787026,  0.42024066],
       [ 0.78338461, -0.38502844]])

In [65]:
a4.reshape(1,16)

array([[-0.34680709,  1.4709312 , -0.85768024, -1.17870434, -0.18514847,
        -2.18952486, -0.22503192,  1.5702648 , -0.36792259, -1.1792732 ,
         0.67730928, -0.98131141,  0.16787026,  0.42024066,  0.78338461,
        -0.38502844]])

In [66]:
a4.reshape(16,1)

array([[-0.34680709],
       [ 1.4709312 ],
       [-0.85768024],
       [-1.17870434],
       [-0.18514847],
       [-2.18952486],
       [-0.22503192],
       [ 1.5702648 ],
       [-0.36792259],
       [-1.1792732 ],
       [ 0.67730928],
       [-0.98131141],
       [ 0.16787026],
       [ 0.42024066],
       [ 0.78338461],
       [-0.38502844]])

In [67]:
a4.reshape(2,-1) # If you give any negative number then numpy will automatically detect the dimmension

array([[-0.34680709,  1.4709312 , -0.85768024, -1.17870434, -0.18514847,
        -2.18952486, -0.22503192,  1.5702648 ],
       [-0.36792259, -1.1792732 ,  0.67730928, -0.98131141,  0.16787026,
         0.42024066,  0.78338461, -0.38502844]])

In [68]:
# If we want to change the array into 3D,4D and so on

In [70]:
a4.reshape(2,2,4)

array([[[-0.34680709,  1.4709312 , -0.85768024, -1.17870434],
        [-0.18514847, -2.18952486, -0.22503192,  1.5702648 ]],

       [[-0.36792259, -1.1792732 ,  0.67730928, -0.98131141],
        [ 0.16787026,  0.42024066,  0.78338461, -0.38502844]]])

In [72]:
a4.reshape(1,1,1,1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[[[[-0.34680709,  1.4709312 , -0.85768024,
                   -1.17870434],
                  [-0.18514847, -2.18952486, -0.22503192,
                    1.5702648 ]],

                 [[-0.36792259, -1.1792732 ,  0.67730928,
                   -0.98131141],
                  [ 0.16787026,  0.42024066,  0.78338461,
                   -0.38502844]]]]]]]]]]]]])

In [75]:
# If we want to extract the data from the list

In [76]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [77]:
a1[0]

'4'

In [78]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [79]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [80]:
a1[::-1] # Reversing the list using ::-1

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [81]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
a2[0]

array([1, 2, 3])

In [84]:
a2[:,1:] # : representing we want all the rows to be selected
        # 1: means we want to select all the columns starting from the 1st index

array([[2, 3],
       [5, 6]])

In [87]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [90]:
a5 = np.random.randint(2,90,(6,5))

In [91]:
print(a5)

[[ 4 71 11 20 21]
 [60 50 43 56 62]
 [68  6 31 68 29]
 [42 75 24  5 33]
 [21 21 82 20 47]
 [83 23 65 38  6]]


In [92]:
# From a5 if we want to extract that data which is greater than 40
a5[a5>40]

array([71, 60, 50, 43, 56, 62, 68, 68, 42, 75, 82, 47, 83, 65])

In [94]:
# If we want to change any data in the a5
a5

array([[ 4, 71, 11, 20, 21],
       [60, 50, 43, 56, 62],
       [68,  6, 31, 68, 29],
       [42, 75, 24,  5, 33],
       [21, 21, 82, 20, 47],
       [83, 23, 65, 38,  6]])

In [96]:
a5[0,1] = 100 # [0,1]-> 71 In previous a5

In [97]:
a5

array([[  4, 100,  11,  20,  21],
       [ 60,  50,  43,  56,  62],
       [ 68,   6,  31,  68,  29],
       [ 42,  75,  24,   5,  33],
       [ 21,  21,  82,  20,  47],
       [ 83,  23,  65,  38,   6]])

In [109]:
a6 = np.random.randint(0,3,(3,3))

In [104]:
a7=np.random.randint(0,3,(3,3))

In [111]:
a6

array([[0, 0, 2],
       [0, 2, 0],
       [1, 0, 1]])

In [112]:
a7

array([[1, 1, 2],
       [1, 2, 1],
       [0, 1, 0]])

In [113]:
a6*a7  # It is not the matrix multiplication it is the element wise multiplication

array([[0, 0, 4],
       [0, 4, 0],
       [0, 0, 0]])

In [115]:
# How to do the matrix multiplication
# Condition-> Column of 1st matrix==Column of 2nd matrix
# Matrix Multiplication -> Symbol=@
a6@a7

array([[0, 2, 0],
       [2, 4, 2],
       [1, 2, 2]])

In [116]:
a6+100

array([[100, 100, 102],
       [100, 102, 100],
       [101, 100, 101]])

In [117]:
a6*2

array([[0, 0, 4],
       [0, 4, 0],
       [2, 0, 2]])

In [118]:
a6/0

C:\Users\gupta\AppData\Local\Temp\ipykernel_11144\1058679823.py:1: RuntimeWarning: divide by zero encountered in divide
  a6/0
C:\Users\gupta\AppData\Local\Temp\ipykernel_11144\1058679823.py:1: RuntimeWarning: invalid value encountered in divide
  a6/0


array([[nan, nan, inf],
       [nan, inf, nan],
       [inf, nan, inf]])

In [119]:
a6**3

array([[0, 0, 8],
       [0, 8, 0],
       [1, 0, 1]], dtype=int32)

In [122]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [125]:
a9=np.ones((4,5))

In [127]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [132]:
a9+np.array([1,2,3,4,5]) # It is doing the row operation

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [137]:
# If we want to do the column wise operation
np.array([[1,2,3,4,5]]).T # T means the transpse operation will not do the transpose because it require more than 1D

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [139]:
np.array([[1,2,3,4]]).T+a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [141]:
a6.T

array([[0, 0, 1],
       [0, 2, 0],
       [2, 0, 1]])

In [142]:
a6

array([[0, 0, 2],
       [0, 2, 0],
       [1, 0, 1]])

In [143]:
a5

array([[  4, 100,  11,  20,  21],
       [ 60,  50,  43,  56,  62],
       [ 68,   6,  31,  68,  29],
       [ 42,  75,  24,   5,  33],
       [ 21,  21,  82,  20,  47],
       [ 83,  23,  65,  38,   6]])

In [144]:
np.sqrt(a5)

array([[ 2.        , 10.        ,  3.31662479,  4.47213595,  4.58257569],
       [ 7.74596669,  7.07106781,  6.55743852,  7.48331477,  7.87400787],
       [ 8.24621125,  2.44948974,  5.56776436,  8.24621125,  5.38516481],
       [ 6.4807407 ,  8.66025404,  4.89897949,  2.23606798,  5.74456265],
       [ 4.58257569,  4.58257569,  9.05538514,  4.47213595,  6.8556546 ],
       [ 9.11043358,  4.79583152,  8.06225775,  6.164414  ,  2.44948974]])

In [145]:
np.exp(a5)

array([[5.45981500e+01, 2.68811714e+43, 5.98741417e+04, 4.85165195e+08,
        1.31881573e+09],
       [1.14200739e+26, 5.18470553e+21, 4.72783947e+18, 2.09165950e+24,
        8.43835667e+26],
       [3.40427605e+29, 4.03428793e+02, 2.90488497e+13, 3.40427605e+29,
        3.93133430e+12],
       [1.73927494e+18, 3.73324200e+32, 2.64891221e+10, 1.48413159e+02,
        2.14643580e+14],
       [1.31881573e+09, 1.31881573e+09, 4.09399696e+35, 4.85165195e+08,
        2.58131289e+20],
       [1.11286375e+36, 9.74480345e+09, 1.69488924e+28, 3.18559318e+16,
        4.03428793e+02]])

In [146]:
np.log10(a5)

array([[0.60205999, 2.        , 1.04139269, 1.30103   , 1.32221929],
       [1.77815125, 1.69897   , 1.63346846, 1.74818803, 1.79239169],
       [1.83250891, 0.77815125, 1.49136169, 1.83250891, 1.462398  ],
       [1.62324929, 1.87506126, 1.38021124, 0.69897   , 1.51851394],
       [1.32221929, 1.32221929, 1.91381385, 1.30103   , 1.67209786],
       [1.91907809, 1.36172784, 1.81291336, 1.5797836 , 0.77815125]])

In [149]:
# Range function
print(list(range(0,10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [150]:
print(list(range(0,10,2)))

[0, 2, 4, 6, 8]


In [151]:
print(list(range(0,10,2.5))) # Floating point is not acceptable

TypeError: 'float' object cannot be interpreted as an integer

In [153]:
np.arange(10) # Same function as range in python

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
# Here floating point numbers are also possible
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [157]:
np.linspace(2,3,num=50) # In between range from 2 to 3 please generate the 50 number

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [160]:
np.linspace(2,3,num=50,retstep=True) # It will also give the step size

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [163]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [164]:
# Here we can also create the new identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])