In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5,6]) # It will convert into the ndarray

array([2, 3, 4, 5, 6])

In [4]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [6]:
np.array([[2,3,4],[4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [8]:
np.array([[1,2,3,4],[2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [9]:
l=[[1,2,3,4],[2,3,4,5]]

In [10]:
print(l[0][0])

1


In [12]:
# We can also define the dimmension
a = np.array([3,4,5,6],ndmin=5)

In [13]:
print(a)

[[[[[3 4 5 6]]]]]


In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.ndim

2

In [20]:
# Creating the data in the numpy
np.random.randint(1,10,(4,4)) # Rows*Column

array([[3, 4, 7, 6],
       [3, 4, 8, 7],
       [8, 9, 8, 5],
       [4, 8, 5, 5]])

In [23]:
np.random.randint(1,10,(4,4,2)) # Rows=4 and Column=4
# Explanation:- We will get the the array of 4 rows and 2 column and we will get the 4 arrays

array([[[3, 1],
        [9, 8],
        [4, 9],
        [8, 2]],

       [[7, 6],
        [8, 5],
        [5, 5],
        [8, 2]],

       [[5, 5],
        [7, 1],
        [7, 5],
        [4, 3]],

       [[8, 8],
        [6, 7],
        [2, 9],
        [3, 6]]])