Agenda
1->Pratical Implemenitation of Stats {Inferential}
2->EDA and Feature Engineering
3-> Interview Stat Question


Chi-Square Test
The test is applied when you have two categorical variables from a single population.It is used to determine wheteher there is a significant association between two variable

In [3]:
import scipy.stats as stats

In [4]:
import seaborn as sns
import pandas as pd
import numpy as np
dataset=sns.load_dataset('tips')

In [5]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
dataset_table=pd.crosstab(dataset['sex'],dataset['smoker'])
print(dataset_table)
# With the help of crosstab we are getting the 2X2 matrix 
# 60 Males are smoker and 97 Males are non smoker
# 33 Female are smoker and 54 Female are non smoker
# Now on these dataset we have to apply the chi-square test

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [7]:
dataset_table.values 

array([[60, 97],
       [33, 54]], dtype=int64)

In [8]:
#Observed Values
Observed_Values = dataset_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[60 97]
 [33 54]]


In [9]:
val=stats.chi2_contingency(dataset_table)

In [10]:
val

Chi2ContingencyResult(statistic=0.0, pvalue=1.0, dof=1, expected_freq=array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]]))

T Test
A t-test is a type of inferential statistic which is used to determine if there is a significant difference between the means of two groups which may be related in certain features

T-test has 2 types : 1. one sampled t-test 2. two-sampled t-test.

In [11]:
ages=[10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,20,19,70]

In [12]:
len(ages)

32

In [13]:
import numpy as np
ages_mean=np.mean(ages)
print(ages_mean) # These is the population mean if we are considering the list of the ages as population

30.34375


In [14]:
# Now let's take the sample from the ages dataset
sample_size=10
age_sample = np.random.choice(ages,sample_size)

In [15]:
age_sample

array([55, 28, 70, 27, 28, 10, 50, 26, 21, 17])

In [16]:
from scipy.stats import ttest_1samp
ttest,p_value=ttest_1samp(age_sample,30) # Here 30 is the population mean


In [17]:
# Printing the p-value
print(p_value)

0.6048261578113359


In [18]:
if p_value < 0.05:    # alpha value is 0.05 or 5%
    print(" we are rejecting null hypothesis")
else:
    print("we fail to reject the null hypothesis")

we fail to reject the null hypothesis


Some More Examples

Consider the age of students in a college and in Class A

In [19]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import math
np.random.seed(6)
school_ages=stats.poisson.rvs(loc=18,mu=35,size=1500) # Population-> 1500
classA_ages=stats.poisson.rvs(loc=18,mu=30,size=25) # Sample which is taken from the population Sample-> 25
# Here we are assumig the distribution so here we are assuming the poison distribution
# mu->mean # loc-> standard deviation # size-> It generates the random values here it will generate 1500  random values

In [20]:
np.mean(school_ages)

53.303333333333335

In [21]:
np.mean(classA_ages)

48.2

In [22]:
# Null Hypothesis Mean = 53.303333333333335
# Altenate Hypothesis != 53.303333333333335

In [23]:
_,p_value=stats.ttest_1samp(a=classA_ages,popmean=school_ages.mean())

In [24]:
print(p_value)

3.26936314797003e-05


In [25]:
school_ages.mean()

53.303333333333335

In [26]:
if p_value < 0.05:    # alpha value is 0.05 or 5%
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

 we are rejecting null hypothesis


Two-sample T-test With Python
The Independent Samples t Test or 2-sample t-test compares the means of two independent groups in order to determine whether there is statistical evidence that the associated population means are significantly different. The Independent Samples t Test is a parametric test. This test is also known as: Independent t Test

In [27]:
np.random.seed(12)
ClassB_ages=stats.poisson.rvs(loc=18,mu=33,size=60)
ClassB_ages.mean()

50.63333333333333

In [28]:
_,p_value=stats.ttest_ind(a=classA_ages,b=ClassB_ages,equal_var=False) # Here we are getting the two value first one is not important that is why we are using the placeholder and other one is p-value

In [29]:
p_value

0.06021969607248899

In [30]:
if p_value < 0.05:    # alpha value is 0.05 or 5%
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

we are accepting null hypothesis


Paired T-test With Python
When you want to check how different samples from the same group are, you can go for a paired T-test

In [31]:
weight1=[25,30,28,35,28,34,26,29,30,26,28,32,31,30,45]
weight2=weight1+stats.norm.rvs(scale=5,loc=-1.25,size=15)

In [32]:
print(weight1)
print(weight2)

[25, 30, 28, 35, 28, 34, 26, 29, 30, 26, 28, 32, 31, 30, 45]
[30.57926457 34.91022437 29.00444617 30.54295091 19.86201983 37.57873174
 18.3299827  21.3771395  36.36420881 32.05941216 26.93827982 29.519014
 26.42851213 30.50667769 41.32984284]


In [33]:
weight_df=pd.DataFrame({"weight_10":np.array(weight1),
                         "weight_20":np.array(weight2),
                       "weight_change":np.array(weight2)-np.array(weight1)})

In [34]:
weight_df

weight_10  weight_20  weight_change
0          25  30.579265       5.579265
1          30  34.910224       4.910224
2          28  29.004446       1.004446
3          35  30.542951      -4.457049
4          28  19.862020      -8.137980
5          34  37.578732       3.578732
6          26  18.329983      -7.670017
7          29  21.377139      -7.622861
8          30  36.364209       6.364209
9          26  32.059412       6.059412
10         28  26.938280      -1.061720
11         32  29.519014      -2.480986
12         31  26.428512      -4.571488
13         30  30.506678       0.506678
14         45  41.329843      -3.670157

In [35]:
_,p_value=stats.ttest_rel(a=weight1,b=weight2)

In [36]:
print(p_value)

0.5732936534411279


Correlation

In [37]:
import seaborn as sns
df1=sns.load_dataset('iris')

In [38]:
df1.shape

(150, 5)

In [39]:
df1.corr(numeric_only='False')

sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

In [40]:
sns.pairplot(df)

NameError: name 'df' is not defined

## Anova Test(F-Test)
The t-test works well when dealing with two groups, but sometimes we want to compare more than two groups at the same time.


For example, if we wanted to test whether petal_width age differs based on some categorical variable like species, we have to compare the means of each level or group the variable

### One Way F-test(Anova) :-
It tell whether two or more groups are similar or not based on their mean similarity and f-score.

Example : there are 3 different category of iris flowers and their petal width and need to check whether all 3 group are similar or not 


In [ ]:
df_anova = df1[['petal_width','species']]

In [ ]:
df_anova

petal_width    species
0            0.2     setosa
1            0.2     setosa
2            0.2     setosa
3            0.2     setosa
4            0.2     setosa
..           ...        ...
145          2.3  virginica
146          1.9  virginica
147          2.0  virginica
148          2.3  virginica
149          1.8  virginica

[150 rows x 2 columns]

Null Hypotheis:- averagemeanspetal(width)(setosa)=averagemeans(width)(versicolor)=averagemeans(width)(virginica)

Alternate Hypothesis:- averagemeanspetal(width)(setosa)!=averagemeans(width)(versicolor)!=averagemeans(width)(virginica)

In [ ]:
grps = pd.unique(df_anova.species.values)

In [ ]:
grps

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
d_data = {grp:df_anova['petal_width'][df_anova.species == grp] for grp in grps}

In [ ]:
d_data

{'setosa': 0     0.2
 1     0.2
 2     0.2
 3     0.2
 4     0.2
 5     0.4
 6     0.3
 7     0.2
 8     0.2
 9     0.1
 10    0.2
 11    0.2
 12    0.1
 13    0.1
 14    0.2
 15    0.4
 16    0.4
 17    0.3
 18    0.3
 19    0.3
 20    0.2
 21    0.4
 22    0.2
 23    0.5
 24    0.2
 25    0.2
 26    0.4
 27    0.2
 28    0.2
 29    0.2
 30    0.2
 31    0.4
 32    0.1
 33    0.2
 34    0.2
 35    0.2
 36    0.2
 37    0.1
 38    0.2
 39    0.2
 40    0.3
 41    0.3
 42    0.2
 43    0.6
 44    0.4
 45    0.3
 46    0.2
 47    0.2
 48    0.2
 49    0.2
 Name: petal_width, dtype: float64,
 'versicolor': 50    1.4
 51    1.5
 52    1.5
 53    1.3
 54    1.5
 55    1.3
 56    1.6
 57    1.0
 58    1.3
 59    1.4
 60    1.0
 61    1.5
 62    1.0
 63    1.4
 64    1.3
 65    1.4
 66    1.5
 67    1.0
 68    1.5
 69    1.1
 70    1.8
 71    1.3
 72    1.5
 73    1.2
 74    1.3
 75    1.4
 76    1.4
 77    1.7
 78    1.5
 79    1.0
 80    1.1
 81    1.0
 82    1.2
 83    1.6
 84    1.5
 85  

In [ ]:
F, p = stats.f_oneway(d_data['setosa'], d_data['versicolor'], d_data['virginica'])

In [ ]:
print(p)

4.1694458394430593e-85


In [ ]:
if p<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

reject null hypothesis


In [45]:
# Example
# Generate a random array of 50 numbers having mean 110 and sd 15
import math
from statsmodels.stats.weightstats import ztest
from numpy.random import randn
mean_iq = 110
sd_iq = 15/math.sqrt(50)
alpha =0.05
null_mean =100
data = sd_iq*randn(50)+mean_iq # Generating 50 random variables

In [46]:
# print mean and sd
print('mean=%.2f stdv=%.2f' % (np.mean(data), np.std(data)))

mean=109.68 stdv=2.24


In [48]:
# now we perform the test. In this function, we passed data, in the value parameter
# we passed mean value in the null hypothesis, in alternative hypothesis we check whether the
# mean is larger

ztest_Score, p_value= ztest(data,value = null_mean)
# the function outputs a p_value and z-score corresponding to that value, we compare the
# p-value with alpha, if it is greater than alpha then we do not null hypothesis
# else we reject it.

if(p_value < alpha):
    print("Reject Null Hypothesis")
else:
    print("Fail to Reject NUll Hypothesis")

Reject Null Hypothesis
